name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3

    - name: 'Setup PHP'
      uses: 'shivammathur/setup-php@v2'
      with:
        php-version: '8.0'
        coverage: 'none'
        extensions: 'curl, json, intl, mbstring, mongodb, openssl'    

    - name: 'Install Composer dependencies' 
      uses : 'php-actions/composer@v6'
      with:
        php_extensions: mongodb

    # - uses: php-actions/phpunit@v3
    #   with:
    #     version
    - name: 'Run unit tests'
      run: |
        vendor/bin/phpunit
 
    # ... then your own project steps ...