name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: 'PHPUnit (PHP ${{ matrix.php-version }}, Symfony ${{ matrix.symfony-version }} + ${{ matrix.dependencies }} deps)'
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.1'
          - '8.4'
        symfony-version:
          - '^5.4'
          - '^6.4'
          - '^7.2'
        dependencies:
          - 'highest'
        exclude:
          - php-version: '8.1'
            symfony-version: '^7.2'
        include:
          - php-version: '7.4'
            symfony-version: '^4.4'
            dependencies: 'highest'
          - php-version: '7.4'
            symfony-version: '^5.0'
            dependencies: 'lowest'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3

    - name: 'Setup PHP'
      uses: 'shivammathur/setup-php@v2'
      with:
        php-version: '${{ matrix.php-version }}'
        coverage: 'none'
        tools: 'composer:v2, flex'
        extensions: 'curl, json, intl, mbstring, mongodb, openssl'

    - name: 'Install Composer dependencies' 
      uses : 'ramsey/composer-install@v2'
      with:
        dependency-versions: "${{ matrix.dependencies }}"
        composer-options: "--no-interaction"
      env:
        COMPOSER_FUND: '0'
        SYMFONY_REQUIRE: '${{ matrix.symfony-version }}'

    - name: 'Run unit tests'
      run: |
        vendor/bin/phpunit
